name: Check Hoodie Available

on:
  # Run on push for testing purposes
  push:
  schedule:
    - cron: "0 * * * *" 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Run command
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python hoodie.py
